swagger: "2.0"
info:
  version: "1.0.0"
  title: "Dial Code Lookup API"
basePath: "/"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /lookup:
    get:
      summary: "Lookup Dial Code information"
      description: "Get a list of all Dial Code records or lookup a specific record by country, E.164 prefix, MCCMNC, or secondary MCCMNC"
      parameters:
        - name: Country
          in: query
          description: "The name of the country to lookup. Example: 'EGYPT'."
          type: string
        - name: prefix_e164
          in: query
          description: "The E.164 prefix to lookup. Example: '20'."
          type: integer
        - name: mccmnc_e212
          in: query
          description: "The E.212 MCCMNC code to lookup. Example: '60203'."
          type: integer
        - name: mccmnc_secondary
          in: query
          description: "The secondary MCCMNC code to lookup. Example: '1234'."
          type: string
      responses:
        "200":
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/DialCode"
        "400":
          description: "Bad request response"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Invalid query parameter(s)."
        "404":
          description: "Not found response"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "No results found for the given query."

definitions:
  DialCode:
    type: "object"
    properties:
      prefix_e164:
        type: "integer"
        example: 202
        description: "The E.164 prefix."
      Country:
        type: "string"
        example: "EGYPT"
        description: "The name of the country."
      Network Description:
        type: "string"
        example: "Mobile - Etisalat"
        description: "A brief description of the network type and operator."
      mccmnc_e212:
        type: "integer"
        example: 60203
        description: "The E.212 MCCMNC code."
      mccmnc_secondary:
        type: "string"
        example: "602 602999"
        description: "The secondary MCCMNC code, if applicable."
